#rm(list=ls())
#gen <- read.table('01-2023.csv', header=T,sep = ';') 
# head(gen[,c(1,4)])
# genx <- as.data.frame(gen[,c(1,4)])
# genred <- aggregate(genx$intensidad,by=list(id=genx$id),mean)
# head(genred)
# write.csv(genred, file='genred.csv')

# rm(list=ls())
# feb <- read.table('02-2023.csv', header=T,sep = ';')
# head(feb[,c(1,4)])
# febx <- as.data.frame(feb[,c(1,4)])
# febred <- aggregate(febx$intensidad,by=list(id=febx$id),mean)
# head(febred)
# write.csv(febred, file='febred.csv')

# rm(list=ls())
# mar <- read.table('03-2022.csv', header=T,sep = ';')  
# head(mar[,c(1,4)])
# marx <- as.data.frame(mar[,c(1,4)])
# marred <- aggregate(marx$intensidad,by=list(id=marx$id),mean)
# head(marred)
# write.csv(marred, file='marred.csv')

# rm(list=ls())
# apr <- read.table('04-2022.csv', header=T,sep = ';')  
# head(apr[,c(1,4)])
# aprx <- as.data.frame(apr[,c(1,4)])
# aprred <- aggregate(aprx$intensidad,by=list(id=aprx$id),mean)
# head(aprred)
# write.csv(aprred, file='aprred.csv')

# rm(list=ls())
# mag <- read.table('05-2022.csv', header=T,sep = ';')  
# head(mag[,c(1,4)])
# magx <- as.data.frame(mag[,c(1,4)])
# magred <- aggregate(magx$intensidad,by=list(id=magx$id),mean)
# head(magred)
# write.csv(magred, file='magred.csv')

# rm(list=ls())
# giu <- read.table('06-2022.csv', header=T,sep = ';')  
# head(giu[,c(1,4)])
# giux <- as.data.frame(giu[,c(1,4)])
# giured <- aggregate(giux$intensidad,by=list(id=giux$id),mean)
# head(giured)
# write.csv(giured, file='giured.csv')

# rm(list=ls())
# lug <- read.table('07-2022.csv', header=T,sep = ';')  
# head(lug[,c(1,4)])
# lugx <- as.data.frame(lug[,c(1,4)])
# lugred <- aggregate(lugx$intensidad,by=list(id=lugx$id),mean)
# head(lugred)
# write.csv(lugred, file='lugred.csv')

# rm(list=ls())
# ago <- read.table('08-2022.csv', header=T,sep = ';')  
# head(ago[,c(1,4)])
# agox <- as.data.frame(ago[,c(1,4)])
# agored <- aggregate(agox$intensidad,by=list(id=agox$id),mean)
# head(agored)
# write.csv(agored, file='agored.csv')

# rm(list=ls())
# set <- read.table('09-2022.csv', header=T,sep = ';')  
# head(set[,c(1,4)])
# setx <- as.data.frame(set[,c(1,4)])
# setred <- aggregate(setx$intensidad,by=list(id=setx$id),mean)
# head(setred)
# write.csv(setred, file='setred.csv')

# rm(list=ls())
# ott <- read.table('10-2022.csv', header=T,sep = ';')  
# head(ott[,c(1,4)])
# ottx <- as.data.frame(ott[,c(1,4)])
# ottred <- aggregate(ottx$intensidad,by=list(id=ottx$id),mean)
# head(ottred)
# write.csv(ottred, file='ottred.csv')

# rm(list=ls())
# nov <- read.table('11-2022.csv', header=T,sep = ';')  
# head(nov[,c(1,4)])
# novx <- as.data.frame(nov[,c(1,4)])
# novred <- aggregate(novx$intensidad,by=list(id=novx$id),mean)
# head(novred)
# write.csv(novred, file='novred.csv')

# rm(list=ls())
# dic <- read.table('12-2022.csv', header=T,sep = ';')  
# head(dic[,c(1,4)])
# dicx <- as.data.frame(dic[,c(1,4)])
# dicred <- aggregate(dicx$intensidad,by=list(id=dicx$id),mean)
# head(dicred)
# write.csv(dicred, file='dicred.csv')

# rm(list=ls())
# gen <- read.csv('genred.csv')  
# feb <- read.csv('febred.csv') 
# mar <- read.csv('marred.csv') 
# apr <- read.csv('aprred.csv') 
# mag <- read.csv('magred.csv') 
# giu <- read.csv('giured.csv') 
# lug <- read.csv('lugred.csv') 
# ago <- read.csv('agored.csv') 
# set <- read.csv('setred.csv') 
# ott <- read.csv('ottred.csv') 
# nov <- read.csv('novred.csv') 
# dic <- read.csv('dicred.csv')
# 
# tot <- rbind(gen,feb,mar,apr,mag,giu,lug,ago,set,ott,nov,dic)
# totred <- aggregate(tot$x,by=list(id=tot$id),mean)
# head(totred)
# write.csv(totred, file='totred.csv')

rm(list=ls())
totred <- read.csv('totred.csv')
coord <- read.table('point ubication.csv', header=T,sep = ';') 
head(coord)
head(totred)

df <- merge(totred, coord[c("id", "utm_x", "utm_y", "longitud", "latitud")],  by = c("id"))
head(df)

write.csv(df, file='traffic_points.csv')
